global using GyverMatrix.Interfaces;
global using System;
global using System.Globalization;
global using System.Reflection;
global using System.Resources;
global using System.Threading.Tasks;
global using Xamarin.Essentials;
global using Xamarin.Forms;
global using Xamarin.Forms.Xaml;